// Publieke prijzenpagina (/pricing): alles wat je vóór het kopen moet weten.
// Bedragen en aantallen komen uit src/modules/billing/plans.ts, niet uit deze tekst.
export const pricing = {
  metaTitle: 'Pricing',
  metaDescription: 'Unlisted has no subscription. Your first search is free; after that you buy credits in one-off packs. Prices include VAT.',
  eyebrow: 'Pricing',
  title: 'Pay per search. No subscription.',
  intro: 'Your first search is free. After that you buy credits in one-off packs, and every search costs one credit.',
  inclVat: 'incl. VAT',
  perSearch: (price: string) => `${price} per search`,
  credits: (credits: number) => `${credits} credits`,
  popular: 'Most popular',
  cta: 'Start with a free search',
  rulesTitle: 'How credits work',
  rules: [
    'One search costs one credit, whether you start it yourself or your agent runs it on a schedule.',
    'A search can return zero or more results. A search with no results still costs one credit.',
    'If a search fails because of an error on our side, the credit goes back to your balance automatically.',
    'Credits don’t expire as long as your account exists. There is no subscription and nothing renews automatically.',
    'Any credit pack unlocks automations: automatic searches and sending emails through Unlisted.',
    'Prices are in euros and include 21% Dutch VAT. You pay via Mollie (iDEAL, card and more).',
  ],
  resultsNote:
    'Results are opportunity signals and published vacancies. A signal is not a confirmed vacancy, and matches are suggestions, partly generated by AI.',
  withdrawalTitle: 'Refunds and your right of withdrawal',
  withdrawalBody:
    'Credits are digital content that is delivered right away. Before you pay, you agree to immediate delivery, and your 14-day right of withdrawal ends once the credits are added. As a courtesy, we refund a pack bought in the last 14 days as long as none of its credits have been used.',
  withdrawalLink: 'Read the full terms',
};
