import { localizeHref, PUBLIC_PATHS } from '@/i18n/routing';
import { absoluteUrl } from '@/lib/seo';
import { CREDIT_PACKS, formatMoney, FREE_WELCOME_CREDITS } from '@/modules/billing/plans';
import { COMPANY, COMPANY_ADDRESS } from '@/shared/constants/company';

// GET /llms.txt — korte, feitelijke samenvatting voor AI-assistenten (https://llmstxt.org).
// Alles komt uit dezelfde bronnen als de site zelf (prijzen, bedrijfsgegevens), dus het loopt nooit uit de pas.
export const dynamic = 'force-static';

const PAGE_NAMES: Record<(typeof PUBLIC_PATHS)[number], string> = {
  '/': 'Home: what Unlisted is and how it works',
  '/pricing': 'Pricing: credit packs, what a credit buys, refunds',
  '/faq': 'FAQ: credits, payments, searches, emails, account and privacy',
  '/contact': 'Contact and support',
  '/privacy': 'Privacy policy',
  '/terms': 'Terms of service',
};

export function GET() {
  const packs = CREDIT_PACKS.map((pack) => `- ${pack.name}: ${pack.credits} credits for ${formatMoney(pack.amountCents, 'en')} incl. VAT`).join('\n');
  const pages = PUBLIC_PATHS.map((path) => `- [${PAGE_NAMES[path]}](${absoluteUrl(localizeHref(path, 'en'))}) (Dutch: ${absoluteUrl(localizeHref(path, 'nl'))})`).join('\n');

  const body = `# Unlisted

> Unlisted helps international students in the Netherlands find jobs, internships and other opportunities before they are posted as vacancies. An agent watches public company signals (news, funding, hiring activity, expansion), matches them to the student's profile and helps write a personal email to the company.

Unlisted is a product of ${COMPANY.legalName} (${COMPANY_ADDRESS}, the Netherlands; Chamber of Commerce ${COMPANY.kvk}). Contact: ${COMPANY.email}.

## How it works

1. The student creates a profile (study, skills, languages, preferred locations, optional CV).
2. A search looks for companies and opportunity signals that fit, and scores each match.
3. The student reviews matches with an explanation of why they fit.
4. Unlisted drafts a personal email; the student sends it, approves it, or explicitly allows automatic sending within a daily limit.

Results are a mix of published vacancies and opportunity signals. An opportunity signal is not a confirmed vacancy. Match scores and email drafts are partly generated by AI and can contain mistakes.

## Pricing

No subscription. New accounts get ${FREE_WELCOME_CREDITS} free credit, so the first search is free. One search costs one credit, also when it finds nothing; a search that fails because of an error is refunded automatically. Credits do not expire while the account exists. Payments via Mollie.

${packs}

## Pages

${pages}
`;

  return new Response(body, { headers: { 'content-type': 'text/plain; charset=utf-8' } });
}
